# Generated by Django 3.1.4 on 2023-02-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swan',
            old_name='int0',
            new_name='rate',
        ),
    ]
