# Generated by Django 3.1.4 on 2023-02-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAPI', '0002_auto_20230221_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detector',
            old_name='_id',
            new_name='idd',
        ),
        migrations.RenameField(
            model_name='swan',
            old_name='_id',
            new_name='idd',
        ),
    ]
