# Generated by Django 3.1.4 on 2023-02-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerAPI', '0004_auto_20230221_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swan',
            old_name='rate',
            new_name='int0',
        ),
    ]
